name: x384
model_type: ImageRestorationModel
scale: 1
num_gpu: 2
manual_seed: 42

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: /home/zqk/data/GS-Blur-Split/train/target
    dataroot_lq: /home/zqk/data/GS-Blur-Split/train/input_noise

    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 384
    use_flip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 3
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: /home/zqk/data/GS-Blur-Split/test/target
    dataroot_lq: /home/zqk/data/GS-Blur-Split/test/input_noise
    io_backend:
      type: disk

network_g:
  type: OmniFreqDeblur_Arch
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [6, 6, 12]
  ffn_expansion_factor: 3.0
  bias: false

path:
  pretrain_network_g:    ~
  strict_load_g:
  resume_state:     ~

train:
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-3   
    betas: [0.9, 0.9]
con
  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100000
    eta_min: 1.0e-7

  total_iter: 100000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean


val:
  val_freq: 10000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 2500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500